<?php

namespace App\Http\Controllers;

use App\Models\GuardRotation;
use App\Models\GuardDuty;
use App\Models\Employee;
use Illuminate\Http\Request;
use Carbon\Carbon;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class GuardRotationController extends Controller
{
    use AuthorizesRequests;

    /**
     * Listado de rotaciones de guardia.
     */
    public function index()
    {
        $this->authorize('viewAny', GuardRotation::class);

        $rotations = GuardRotation::orderBy('name')->paginate(10);
        return view('guard-rotations.index', compact('rotations'));
    }

    /**
     * Formulario para crear una nueva rotación.
     */
    public function create()
    {
        $this->authorize('create', GuardRotation::class);
        $employees = Employee::orderBy('first_name')->get();

        return view('guard-rotations.create', compact('employees'));
    }

    /**
     * Almacena una nueva rotación.
     */
    public function store(Request $request)
    {
        $this->authorize('create', GuardRotation::class);

        $validated = $request->validate([
            'name' => 'required|string|max:100|unique:guard_rotations,name',
            'description' => 'nullable|string',
            'is_active' => 'boolean',
            'employee_a_id' => 'nullable|exists:employees,id',
            'employee_b_id' => 'nullable|exists:employees,id',
            'employee_c_id' => 'nullable|exists:employees,id',
            'employee_d_id' => 'nullable|exists:employees,id',
        ]);

        $guardRotation = GuardRotation::create($validated);
        $this->autoGenerateDuties($guardRotation, now()->year, now()->month);

        return redirect()->route('guard-rotations.index')
            ->with('success', 'Rotación creada correctamente.');
    }

    /**
     * Muestra el detalle de una rotación (redirige al calendario).
     */
    public function show(GuardRotation $guardRotation)
    {
        return redirect()->route('guard-rotations.calendar', $guardRotation);
    }

    /**
     * Formulario para editar una rotación.
     */
    public function edit(GuardRotation $guardRotation)
    {
        $this->authorize('update', $guardRotation);
        $employees = Employee::orderBy('first_name')->get();

        return view('guard-rotations.edit', compact('guardRotation', 'employees'));
    }

    /**
     * Actualiza una rotación existente.
     */
    public function update(Request $request, GuardRotation $guardRotation)
    {
        $this->authorize('update', $guardRotation);

        $validated = $request->validate([
            'name' => 'required|string|max:100|unique:guard_rotations,name,' . $guardRotation->id,
            'description' => 'nullable|string',
            'is_active' => 'boolean',
            'employee_a_id' => 'nullable|exists:employees,id',
            'employee_b_id' => 'nullable|exists:employees,id',
            'employee_c_id' => 'nullable|exists:employees,id',
            'employee_d_id' => 'nullable|exists:employees,id',
        ]);

        $guardRotation->update($validated);

        return redirect()->route('guard-rotations.index')
            ->with('success', 'Rotación actualizada correctamente.');
    }

    /**
     * Elimina una rotación.
     */
    public function destroy(GuardRotation $guardRotation)
    {
        $this->authorize('delete', $guardRotation);

        $guardRotation->delete();

        return redirect()->route('guard-rotations.index')
            ->with('success', 'Rotación eliminada correctamente.');
    }

    /**
     * Muestra el calendario interactivo para una rotación específica.
     */
    public function calendar(Request $request, GuardRotation $guardRotation)
    {
        $this->authorize('view', $guardRotation);
        $guardRotation->load(['employeeA', 'employeeB', 'employeeC', 'employeeD']);

        $month = (int) $request->input('month', now()->month);
        $year = (int) $request->input('year', now()->year);
        
        $this->autoGenerateDuties($guardRotation, $year, $month);
        
        $date = Carbon::createFromDate($year, $month, 1);

        $employees = Employee::orderBy('first_name')->get(['id', 'first_name', 'last_name', 'id_number']);

        return view('guard-rotations.calendar', compact('guardRotation', 'date', 'employees'));
    }

    /**
     * API JSON: devuelve los datos de un mes para una rotación.
     */
    public function data(Request $request, GuardRotation $guardRotation)
    {
        $this->authorize('view', $guardRotation);

        $month = (int) $request->input('month', now()->month);
        $year = (int) $request->input('year', now()->year);

        $this->autoGenerateDuties($guardRotation, $year, $month);

        $duties = GuardDuty::where('guard_rotation_id', $guardRotation->id)
            ->whereYear('date', $year)
            ->whereMonth('date', $month)
            ->with('employee:id,first_name,last_name')
            ->get()
            ->keyBy(fn($d) => $d->date->format('Y-m-d'));

        return response()->json($duties);
    }

    /**
     * Genera automáticamente la secuencia A-B-C-D para un mes.
     */
    public function generate(Request $request, GuardRotation $guardRotation)
    {
        $this->authorize('update', $guardRotation);

        if (!$guardRotation->employee_a_id || !$guardRotation->employee_b_id || !$guardRotation->employee_c_id || !$guardRotation->employee_d_id) {
            return redirect()
                ->route('guard-rotations.edit', $guardRotation)
                ->with('error', 'Debe configurar la codificación de técnicos para todas las letras (A, B, C, D) antes de generar el rol mensual.');
        }

        $month = (int) $request->input('month', now()->month);
        $year = (int) $request->input('year', now()->year);
        $startDate = Carbon::createFromDate($year, $month, 1);
        $daysInMonth = $startDate->daysInMonth;

        GuardDuty::where('guard_rotation_id', $guardRotation->id)
            ->whereYear('date', $year)
            ->whereMonth('date', $month)
            ->delete();

        $letters = ['A', 'B', 'C', 'D'];
        $mapping = [
            'A' => $guardRotation->employee_a_id,
            'B' => $guardRotation->employee_b_id,
            'C' => $guardRotation->employee_c_id,
            'D' => $guardRotation->employee_d_id,
        ];

        for ($day = 1; $day <= $daysInMonth; $day++) {
            $letter = $letters[($day - 1) % 4];
            GuardDuty::create([
                'guard_rotation_id' => $guardRotation->id,
                'date' => $startDate->copy()->day($day),
                'letter' => $letter,
                'employee_id' => $mapping[$letter],
            ]);
        }

        return redirect()
            ->route('guard-rotations.calendar', ['guard_rotation' => $guardRotation, 'month' => $month, 'year' => $year])
            ->with('success', 'Mes generado correctamente.');
    }

    /**
     * Actualiza un día específico vía AJAX.
     */
    public function updateDay(Request $request, GuardRotation $guardRotation)
    {
        $this->authorize('update', $guardRotation);

        $validated = $request->validate([
            'date' => 'required|date',
            'letter' => 'required|in:A,B,C,D',
            'employee_id' => 'nullable|exists:employees,id',
            'notes' => 'nullable|string|max:255',
            'apply_to_all' => 'nullable|boolean',
        ]);

        $date = Carbon::parse($validated['date']);

        $duty = GuardDuty::updateOrCreate(
            [
                'guard_rotation_id' => $guardRotation->id,
                'date' => $date->format('Y-m-d'),
            ],
            [
                'letter' => $validated['letter'],
                'employee_id' => $validated['employee_id'],
                'notes' => $validated['notes'],
            ]
        );

        if (!empty($validated['apply_to_all']) && $validated['apply_to_all']) {
            GuardDuty::where('guard_rotation_id', $guardRotation->id)
                ->whereYear('date', $date->year)
                ->whereMonth('date', $date->month)
                ->where('letter', $validated['letter'])
                ->update(['employee_id' => $validated['employee_id']]);
        }

        $duty->load('employee:id,first_name,last_name');

        return response()->json([
            'success' => true,
            'duty' => $duty,
            'message' => 'Guardia actualizada correctamente.'
        ]);
    }

    /**
     * Genera y descarga el PDF del "Roll de Guardia 24x72".
     */
    public function pdf(Request $request, GuardRotation $guardRotation)
    {
        $this->authorize('view', $guardRotation);

        $month = (int) $request->input('month', now()->month);
        $year = (int) $request->input('year', now()->year);

        $this->autoGenerateDuties($guardRotation, $year, $month);

        $date = Carbon::createFromDate($year, $month, 1);

        $duties = GuardDuty::where('guard_rotation_id', $guardRotation->id)
            ->whereYear('date', $year)
            ->whereMonth('date', $month)
            ->orderBy('date')
            ->get()
            ->keyBy(fn($d) => $d->date->day);

        $guardRotation->load(['employeeA', 'employeeB', 'employeeC', 'employeeD']);
        $letterEmployees = [
            'A' => $guardRotation->employeeA,
            'B' => $guardRotation->employeeB,
            'C' => $guardRotation->employeeC,
            'D' => $guardRotation->employeeD,
        ];

        $daysInMonth = $date->daysInMonth;
        $firstDayOfWeek = $date->copy()->startOfMonth()->dayOfWeek;
        $startOffset = ($firstDayOfWeek === 0) ? 6 : $firstDayOfWeek - 1;

        $weeks = [];
        $currentDay = 1;
        for ($i = 0; $i < 6; $i++) {
            $week = [];
            for ($j = 0; $j < 7; $j++) {
                if (($i === 0 && $j < $startOffset) || $currentDay > $daysInMonth) {
                    $week[] = null;
                } else {
                    $week[] = $currentDay;
                    $currentDay++;
                }
            }
            $weeks[] = $week;
            if ($currentDay > $daysInMonth) {
                break;
            }
        }

        $pdf = Pdf::loadView('guard-rotations.pdf', compact(
            'guardRotation', 'date', 'weeks', 'duties', 'letterEmployees'
        ));
        $pdf->setPaper('a4', 'landscape');

        return $pdf->download('roll-guardia-' . $guardRotation->name . '-' . $date->format('m-Y') . '.pdf');
    }

    /**
     * Widget para mostrar las guardias activas hoy.
     */
    public function todayWidget()
    {
        $today = now()->toDateString();
        $rotations = GuardRotation::where('is_active', true)->get();

        $guardiasHoy = [];
        foreach ($rotations as $rotation) {
            $duty = GuardDuty::where('guard_rotation_id', $rotation->id)
                ->whereDate('date', $today)
                ->with('employee.position')
                ->first();

            if ($duty) {
                $guardiasHoy[] = [
                    'rotation' => $rotation->name,
                    'letter' => $duty->letter,
                    'employee' => $duty->employee,
                    'notes' => $duty->notes,
                ];
            }
        }

        return view('guard-duties.today-widget', compact('guardiasHoy'));
    }

    /**
     * Auto-generate sequence (A-B-C-D) for a rotation in a specific month if not exists.
     */
    private function autoGenerateDuties(GuardRotation $guardRotation, $year, $month)
    {
        if (!$guardRotation->employee_a_id || !$guardRotation->employee_b_id || !$guardRotation->employee_c_id || !$guardRotation->employee_d_id) {
            return false;
        }

        $exists = GuardDuty::where('guard_rotation_id', $guardRotation->id)
            ->whereYear('date', $year)
            ->whereMonth('date', $month)
            ->exists();

        if ($exists) {
            return false;
        }

        $startDate = Carbon::createFromDate($year, $month, 1);
        $daysInMonth = $startDate->daysInMonth;

        $letters = ['A', 'B', 'C', 'D'];
        $mapping = [
            'A' => $guardRotation->employee_a_id,
            'B' => $guardRotation->employee_b_id,
            'C' => $guardRotation->employee_c_id,
            'D' => $guardRotation->employee_d_id,
        ];

        for ($day = 1; $day <= $daysInMonth; $day++) {
            $letter = $letters[($day - 1) % 4];
            GuardDuty::create([
                'guard_rotation_id' => $guardRotation->id,
                'date' => $startDate->copy()->day($day),
                'letter' => $letter,
                'employee_id' => $mapping[$letter],
            ]);
        }

        return true;
    }
}